---
title: "RLE Analytics - Crypto Daily Report"
author: "Jake Rozran - RLE Analytics"
format:
    html:
        toc: true
        smooth-scroll: true
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}

library(dplyr)
library(ggplot2)
library(scales)
library(readr)
library(lubridate)
library(zoo)
library(gridExtra)
library(tidyr)
library(kableExtra)
library(reticulate)
library(ggrepel)

get_data <- function(token, hotcode) {
    url <- paste0("https://www.coingecko.com/price_charts/export/",
                  hotcode,
                  "/usd.csv")

    dat <- read_csv(url) %>% 
        mutate(token = token,
               date = as_date(as_datetime(snapped_at)),
               yest_price = lag(price)) %>% 
        filter(!is.na(yest_price)) %>% 
        mutate(price_30d = lead(price, 30),
               pc_30d = (price_30d - price) / price,
               price_change = ifelse(yest_price == 0, 0, 
                                     (price - yest_price) / yest_price),
               five2_week_low = rollapply(yest_price, 
                                          width = 365, 
                                          FUN = min,
                                          align = "right", 
                                          partial = TRUE),
               price_to_52wl = price / five2_week_low,
               five2_week_hi  = rollapply(yest_price, 
                                          width = 365, 
                                          FUN = max,
                                          align = "right", 
                                          partial = TRUE),
               price_to_52wh = price / five2_week_hi,
               all_time_high = cummax(yest_price),
               price_to_ath = price / all_time_high,
               all_time_low = cummin(yest_price),
               price_to_atl = price / all_time_low,
               two_hundred_ma = rollapply(yest_price, 
                                          width = 200, 
                                          FUN = mean,
                                          align = "right", 
                                          partial = TRUE),
               fifty_hundred_ma = rollapply(yest_price, 
                                            width = 50, 
                                            FUN = mean,
                                            align = "right", 
                                            partial = TRUE))
    
    return(dat)
}

current_deal <- function(dat, token) {
    current_price <- dat %>% 
        filter(date == max(date)) %>% 
        pull(price)
    
    yesterday_price <- dat %>% 
        filter(date == max(date) - days(1)) %>% 
        pull(price)
    
    high_52w <- dat %>% 
        filter(date >= max(date) - days(365)) %>% 
        summarise(max_price = max(price)) %>% 
        pull(max_price)
    
    low_52w <- dat %>% 
        filter(date >= max(date) - days(365)) %>% 
        summarise(min_price = min(price)) %>% 
        pull(min_price)
    
    market_cap <- (dat %>% 
        filter(date == max(date)) %>% 
        pull(market_cap)) / 1000000000000
    
    yest_vol <- (dat %>% 
        filter(date == max(date) - days(1)) %>% 
        pull(total_volume))  / 1000000000
    
    stats <- tibble(
        `Current Price` = dollar(current_price),
        `Yesterday's Price` = dollar(yesterday_price),
        `52 Week High` = dollar(high_52w),
        `52 Week Low` = dollar(low_52w),
        `Market Cap` = dollar(market_cap, suffix = "T"),
        `Yesterday's Volume` = dollar(yest_vol, suffix = "B")
    )
    
    stats %>%
        kbl() %>%
        kable_minimal()
}

current_deal_price <- function(dat, token) {
    dat %>% 
        filter(date >= Sys.Date() - days(365)) %>% 
        select(date, 
               price, 
               five2_week_low, 
               five2_week_hi,
               two_hundred_ma,
               fifty_hundred_ma) %>% 
        pivot_longer(!date, names_to = "names", values_to = "values") %>% 
        mutate(names = case_when(names == "five2_week_low" ~ "52 Week Low",
                                 names == "five2_week_hi" ~ "52 Week High",
                                 names == "two_hundred_ma" ~ "200 Day Moving Average Price",
                                 names == "fifty_hundred_ma" ~ "50 Day Moving Average Price",
                                 names == "price" ~ "Current Price",
                                 1 == 1 ~ names),
               names = factor(names, 
                              levels = c("Current Price",
                                         "50 Day Moving Average Price",
                                         "200 Day Moving Average Price",
                                         "52 Week High",
                                         "52 Week Low"))) %>%
        ggplot(aes(x = date, y = values, color = names)) + 
            geom_line() + 
            scale_y_continuous(labels = dollar_format()) + 
            # scale_color_brewer(palette = "Blues") + 
            ggtitle(paste0(token, " Daily Price and Metrics")) + 
            theme(panel.background = element_blank(),
                  panel.grid = element_line(color = "light gray"),
                  axis.ticks = element_blank(), 
                  axis.title = element_blank(), 
                  plot.background = element_rect(fill = NA, color = "black"),
                  legend.position = "top",
                  legend.title = element_blank(),
                  legend.key = element_blank()) + 
            guides(color = guide_legend(nrow = 2))
}

current_deal_volume <- function(dat, token) {
    dat %>% 
        filter(date >= Sys.Date() - days(365)) %>% 
        ggplot(aes(x = date, y = total_volume)) +
            geom_bar(stat = "identity", fill = "navy") + 
            ggtitle(paste0(token, " Daily Volumes")) + 
            scale_y_continuous(labels = dollar_format(scale = 1 / 1000000000, 
                                                      suffix = "B")) + 
            theme(panel.background = element_blank(),
                  panel.grid = element_line(color = "light gray"),
                  axis.ticks = element_blank(), 
                  axis.title = element_blank(), 
                  plot.background = element_rect(fill = NA, color = "black"))
}

model_performance <- function(today, dat, token, buy_thresh) {
    csv <- paste0("../../data/one_percent/returns_", tolower(token), ".csv")
    hist <- read_csv(csv) %>% 
        filter(pred_date < Sys.Date() - days(1))
    
    today <- today %>% 
        mutate(train_start = as_date(train_start),
               train_end = as_date(train_end),
               pred_date = as_date(pred_date))
    hist %>% 
        bind_rows(today) %>% 
        write_csv(csv)
    
    hist <- hist %>% 
        bind_rows(today) %>% 
        left_join(dat %>% select(date, pc_30d, price, price_30d), 
                  by = c("pred_date" = "date")) %>% 
        mutate(buy_decision = buy_prob > buy_thresh,
               decision = case_when(is.na(pc_30d) ~ "unknown",
                                    buy_decision == TRUE & pc_30d >= 0 ~ "TP",
                                    buy_decision == TRUE & pc_30d < 0.1 ~ "FP",
                                    buy_decision == FALSE & pc_30d >= 0.1 ~ "FN",
                                    buy_decision == FALSE & pc_30d < 0.1 ~ "TN"),
               color = case_when(decision == "TP" | decision == "TN" ~ "green", 
                                 decision == "FP" | decision == "FN" ~ "red",
                                 is.na(pc_30d) ~ "unknown"),
               shape = ifelse(buy_decision, "o", "x"))
    
    plot_dat <- hist %>% 
        filter(pred_date >= Sys.Date() - days(100)) 
    
    ggplot(plot_dat, aes(x = pred_date)) +
        geom_errorbar(aes(ymin = price, ymax = price_30d, color = color), width = 0) +
        geom_line(aes(y = price)) + 
        geom_point(aes(color = color, shape = shape), size = 2, y = min(plot_dat$price)) + 
        scale_color_manual(values = c("forestgreen", "red", "blue")) + 
        scale_shape_manual(values = c("B", "D", "?")) + 
        scale_y_continuous(labels = dollar_format()) + 
        ggtitle(paste0("Price of ", token, " & Model Decision"),
                subtitle = paste0("Price in 30d Represented by Colored Lines\n", 
                                  "Green: Correct Decision; Red: Incorrect; Blue:",
                                  " Too Recent\nB: Buy; D: Don't Buy")) + 
        theme(panel.background = element_blank(),
              panel.grid.major = element_line(color = "light gray"),
              axis.ticks = element_blank(), 
              axis.title = element_blank(), 
              plot.background = element_rect(fill = NA, color = "black"), 
              strip.background = element_blank(),
              legend.position = "none")
}
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}

## GET DATA FOR BITCOIN
token <- "BTC"
hotcode <- 1

btc <- get_data("BTC", 1)
eth <- get_data("ETH", 279)

tmp <- btc
names(tmp) <- paste0("BTC_", names(tmp))

eth <- eth %>% 
    left_join(tmp, by = c("date" = "BTC_date")) %>% 
    mutate(price_to_btc = price / BTC_price,
           vol_to_btc = total_volume / BTC_total_volume,
           f2wl_to_btc = five2_week_low / BTC_five2_week_low,
           f2wh_to_btc = five2_week_hi / BTC_five2_week_hi,
           pt52wl_diff_btc = price_to_52wl - BTC_price_to_52wl,
           pt52wh_diff_btc = price_to_52wh - BTC_price_to_52wh,
           p2atl_diff_btc = price_to_atl - BTC_price_to_atl,
           p2ath_diff_btc = price_to_ath - BTC_price_to_ath)

tmp <- NULL
```

## Summary

BTC IS A SELL.

## Current Data

### BTC

```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.height = 3, out.width = "100%"}

current_deal(btc, "BTC")
current_deal_price(btc, "BTC")
current_deal_volume(btc, "BTC")
```

### ETH

```{r}
#| echo: false
#| message: false
#| warning: false
#| fig-height: 3
#| out-width: 100%

current_deal(eth, "ETH")
current_deal_price(eth, "ETH")
current_deal_volume(eth, "ETH")
```


## 30 Day Predictions

```{python, echo = FALSE, message = FALSE, warning = FALSE}
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import auc, roc_curve, precision_recall_curve
import numpy as np
import scipy
import matplotlib.pyplot as plt
from datetime import timedelta, datetime

pd.options.mode.chained_assignment = None
```

```{python, echo = FALSE, message = FALSE, warning = FALSE}

def plot_fi(fi, figsize = (12, 7)):
    return fi.plot('cols', 'imp', 'barh', figsize=figsize, legend=False)

def rf_feat_importance(m, df):
    return pd.DataFrame({'cols':df.columns, 'imp':m.feature_importances_}
                       ).sort_values('imp', ascending=False)

def show_roc(clf, X_test, y_test, auc_ret = False):
    # Step 1: Predict probabilities for the positive class
    y_scores = clf.predict_proba(X_test)[:, 1] # Probabilities for the positive class

    # Step 2: Compute TPR, FPR, and threshold values
    fpr, tpr, thresholds = roc_curve(y_test, y_scores)

    # Step 3: Compute the Area Under the Curve (AUC)
    roc_auc = auc(fpr, tpr)

    if auc_ret:
        return roc_auc

def show_prc(clf, X_test, y_test, auc_ret = False):
    # Step 1: Predict probabilities for the positive class
    y_scores = clf.predict_proba(X_test)[:, 1] # Probabilities for the positive class

    # Step 2: Compute TPR, FPR, and threshold values
    precision, recall, thresholds = precision_recall_curve(y_test, y_scores)

    # Step 3: Compute the Area Under the Curve (AUC)
    roc_auc = auc(recall, precision)

    if auc_ret:
        return roc_auc

def get_today_pred(tmp, features):
    train_start = tmp['date'].loc[~tmp['price_to_52wh'].isna()].min()
    train_end = tmp['date'].loc[(~tmp['pc_30d'].isna())].max()
    test_end = tmp['date'].max()
    test_start = test_end - timedelta(days = 1)
    
    # Create the Training Dataset
    train = tmp.loc[(tmp['date'] >= train_start) &
                    (tmp['date'] < train_end)]
    
    X_train = train[features]
    y_train = (train['pc_30d'] >= 0.1).astype(int)
    
    test = tmp.loc[(tmp['date'] >= test_start) & 
                   (tmp['date'] < test_end)]
    
    X_test = test[features]
    
    # Train the model with the training data
    rf = RandomForestClassifier(n_estimators = 1000, n_jobs = -1)
    rf.fit(X_train, y_train)
    
    buy_prob = rf.predict_proba(X_test)[:, 1][0] 
    
    ## SELL
    y_train = (train['pc_30d'] <= 0).astype(int)
    
    rf.fit(X_train, y_train)
    
    sell_prob = rf.predict_proba(X_test)[:, 1][0] 
    
    today = pd.DataFrame({'train_start': train_start.isoformat(),
                          'train_end': train_end.isoformat(),
                          'pred_date': test_start.isoformat(),
                          'buy_prob': buy_prob,
                          'sell_prob': sell_prob}, 
                          index = [0])
    return(today)

```



```{python, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE}

btc_features = ["price_to_52wl", "price_to_52wh", "price_to_ath", "price_to_atl"]
btc_today = get_today_pred(r.btc, btc_features)
eth_features = ["price_to_52wl", "price_to_52wh", "price_to_ath", "price_to_atl",
                "price_to_btc", "vol_to_btc", "f2wl_to_btc", "f2wh_to_btc", 
                "pt52wl_diff_btc", "pt52wh_diff_btc", "p2atl_diff_btc", 
                "p2ath_diff_btc"]
eth_today = get_today_pred(r.eth, eth_features)
```

### BTC

```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.height = 4, out.width = "100%"}
model_performance(py$btc_today, btc, "BTC", 0.13)
```

### ETH

```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.height = 4, out.width = "100%"}
model_performance(py$eth_today, eth, "ETH", 0.6)
```


## 30 Day Price Simulations

```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.height = 9, out.width = "100%", output = "asis"}

mc_sim_present <- function(dat, token) {
    ## MONTE CARLO SIMULATION
    pc <- dat %>% 
        pull(price_change)
    
    iterations <- 10000
    
    ## NEXT 30 DAYS
    start_date <- Sys.Date() - days(1)
    end_date <- Sys.Date() + days(30)
    dates <- as_date(start_date:end_date)
    start_price <- dat$price[dat$date == start_date]
    current_price <- dat$price[dat$date == Sys.Date() - days(1)]
    
    mc_dat <- tibble(date = rep(dates, iterations),
                     iteration = rep(1:iterations, each = length(dates)),
                     price_change = sample(pc, 
                                           iterations * length(dates), 
                                           replace = TRUE)) %>% 
        group_by(iteration) %>% 
        mutate(price_change = ifelse(date == start_date, 
                                     start_price,
                                     1 + price_change),
               price = cumprod(price_change))
    
    perc <- percent(dim(mc_dat %>% 
                            filter(date == max(date) & 
                                       price <= current_price))[1] / iterations,
                    accuracy = 0.01)
    
    lb_95 <- mc_dat %>% 
        filter(date == max(date)) %>% 
        ungroup() %>% 
        summarise(lb95 = quantile(price, 0.025)) %>% 
        pull(lb95)
    
    ub_95 <- mc_dat %>% 
        filter(date == max(date)) %>% 
        ungroup() %>% 
        summarise(ub95 = quantile(price, 0.975)) %>% 
        pull(ub95)
    
    bounds <- paste0("There is a 95% chance that the price of ", token, 
                     " will be between ", dollar(lb_95), " and ", dollar(ub_95), 
                     " in 30 days.\n\n")
    
    cat(bounds)
    
    plot_present <- mc_dat %>% 
        bind_rows(dat %>% 
                      filter(date >= Sys.Date() - days(30) &
                                 date < Sys.Date()) %>% 
                      select(date, price) %>% 
                      mutate(iteration = 0) %>% 
                      rename(actual_price = price)) %>% 
        ggplot(aes(x = date, group = iteration)) +
            geom_line(aes(y = price), alpha = 0.05, na.rm = TRUE) + 
            geom_line(aes(y = actual_price), color = "red", na.rm = TRUE) + 
            scale_y_continuous(labels = dollar_format()) + 
            ggtitle("Simulated Prices for the next 30 Days",
                    subtitle = paste0("Red Line: Actual Prices; Black: Simulated\n",
                                      "Current Price Percentile of Final Simulated",
                                      " Price: ", perc)) + 
            theme(panel.background = element_blank(),
                  panel.grid = element_line(color = "light gray"),
                  axis.ticks = element_blank(), 
                  axis.title = element_blank(), 
                  plot.background = element_rect(fill = NA, color = "black"))
    
    return(plot_present)
    
}

mc_sim_15 <- function(dat, token) {
    pc <- dat %>% 
        pull(price_change)
    
    iterations <- 10000
    
    ## 15 DAYS AGO TO NEXT 15 DAYS
    start_date <- Sys.Date() - days(15)
    end_date <- Sys.Date() + days(15)
    dates <- as_date(start_date:end_date)
    start_price <- dat$price[dat$date == start_date]
    current_price <- dat$price[dat$date == Sys.Date() - days(1)]
    
    mc_dat <- tibble(date = rep(dates, iterations),
                     iteration = rep(1:iterations, each = length(dates)),
                     price_change = sample(pc, 
                                           iterations * length(dates), 
                                           replace = TRUE)) %>% 
        group_by(iteration) %>% 
        mutate(price_change = ifelse(date == start_date, 
                                     start_price,
                                     1 + price_change),
               price = cumprod(price_change))
    
    perc <- dim(mc_dat %>% 
                    filter(date == max(date) & 
                               price <= current_price))[1] / iterations
    expected_15 <- if(perc <= 0.975 & 
                      perc >= 0.025) {
        paste0("The current price of ", token, " is within expected bounds from ",
               "15 days ago.\n\n")
    } else if (perc > 0.975) {
        paste0("The current price of ", token, " is above expected bounds from ",
               "15 days ago.\n\n")
    } else {
        paste0("The current price of ", token, " is below expected bounds from ",
               "15 days ago.\n\n")
    }
    
    cat(expected_15)
    
    plot_15 <- mc_dat %>% 
        bind_rows(dat %>% 
                      filter(date >= Sys.Date() - days(45) &
                                 date < Sys.Date()) %>% 
                      select(date, price) %>% 
                      mutate(iteration = 0) %>% 
                      rename(actual_price = price)) %>% 
        ggplot(aes(x = date, group = iteration)) +
            geom_line(aes(y = price), alpha = 0.1, na.rm = TRUE) + 
            geom_line(aes(y = actual_price), color = "red", na.rm = TRUE) + 
        scale_y_continuous(labels = dollar_format()) + 
            ggtitle("Simulated Prices for the last 15 Days through next 15 Days",
                    subtitle = paste0("Red Line: Actual Prices; Black: Simulated\n",
                                      "Current Price Percentile of Final Simulated",
                                      " Price: ", percent(perc, accuracy = 0.01))) + 
            theme(panel.background = element_blank(),
                  panel.grid = element_line(color = "light gray"),
                  axis.ticks = element_blank(), 
                  axis.title = element_blank(), 
                  plot.background = element_rect(fill = NA, color = "black"))
    
    return(plot_15)

}

mc_sim_30 <- function(dat, token) {
    pc <- dat %>% 
        pull(price_change)
    
    iterations <- 10000
    
    ## 30 DAYS AGO TO TODAY
    start_date <- Sys.Date() - days(31)
    end_date <- Sys.Date() - days(1)
    dates <- as_date(start_date:end_date)
    start_price <- dat$price[dat$date == start_date]
    current_price <- dat$price[dat$date == Sys.Date() - days(1)]
    
    mc_dat <- tibble(date = rep(dates, iterations),
                     iteration = rep(1:iterations, each = length(dates)),
                     price_change = sample(pc, 
                                           iterations * length(dates), 
                                           replace = TRUE)) %>% 
        group_by(iteration) %>% 
        mutate(price_change = ifelse(date == start_date, 
                                     start_price,
                                     1 + price_change),
               price = cumprod(price_change))
    
    perc <- dim(mc_dat %>% 
                    filter(date == max(date) & 
                               price <= current_price))[1] / iterations
    
    expected_30 <- if(perc <= 0.975 & 
                      perc >= 0.025) {
        paste0("The current price of ", token, " is within expected bounds from ",
               "30 days ago.\n\n")
    } else if (perc > 0.975) {
        paste0("The current price of ", token, " is above expected bounds from ",
               "30 days ago.\n\n")
    } else {
        paste0("The current price of ", token, " is below expected bounds from ",
               "30 days ago.\n\n")
    }
    
    cat(expected_30)
    
    plot_30 <- mc_dat %>% 
        bind_rows(dat %>% 
                      filter(date >= Sys.Date() - days(60) &
                                 date < Sys.Date()) %>% 
                      select(date, price) %>% 
                      mutate(iteration = 0) %>% 
                      rename(actual_price = price)) %>% 
        ggplot(aes(x = date, group = iteration)) +
            geom_line(aes(y = price), alpha = 0.1, na.rm = TRUE) + 
            geom_line(aes(y = actual_price), color = "red", na.rm = TRUE) + 
        scale_y_continuous(labels = dollar_format()) + 
            ggtitle("Simulated Prices for the last 30 Days",
                    subtitle = paste0("Red Line: Actual Prices; Black: Simulated\n",
                                      "Current Price Percentile of Final Simulated",
                                      " Price: ", percent(perc, accuracy = 0.01))) + 
            theme(panel.background = element_blank(),
                  panel.grid = element_line(color = "light gray"),
                  axis.ticks = element_blank(), 
                  axis.title = element_blank(), 
                  plot.background = element_rect(fill = NA, color = "black"))
    
    return(plot_30)
}
```

### BTC

```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.height = 9, out.width = "100%", output = "asis"}

btc_plot_present <- mc_sim_present(btc, "BTC")
btc_plot_15 <- mc_sim_15(btc, "BTC")
btc_plot_30 <- mc_sim_30(btc, "BTC")
gridExtra::grid.arrange(btc_plot_present, btc_plot_15, btc_plot_30, nrow = 3)
```

### ETH

```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.height = 9, out.width = "100%", output = "asis"}

eth_plot_present <- mc_sim_present(eth, "ETH")
eth_plot_15 <- mc_sim_15(eth, "ETH")
eth_plot_30 <- mc_sim_30(eth, "ETH")
gridExtra::grid.arrange(eth_plot_present, eth_plot_15, eth_plot_30, nrow = 3)
```


## List of Securities Tracked

- BTC
- ETH